### ISSUE TITLE
Draw volcano plot function in ancom source code

### ISSUE THREAD

**Issue by wanjinhu** [FrederickHuangLin/ANCOM-Code-Archive#43]
hi
when i run step2 ancom of this pipeline, i have some doubts about the volcano plot in the ancom function, specifically:
```r
  # Draw volcano plot
  # Calculate clr
  clr_table = apply(feature_table, 2, clr)
  # Calculate clr mean difference
  eff_size = apply(clr_table, 1, function(y) 
    lm(y ~ x, data = data.frame(y = y, 
                                x = meta_data %>% pull(main_var),
                                check.names = FALSE))$coef[-1])
```
in the first standard process, main_var is Subject which has two factor: subject-1 and subject-2, it is a categorical variable, and when analyzed with _lm_, it will generate dummy variables "xsubject-2  "(_lm_ defaults to the first variable subject-1 as the control variable) like this:
```
Coefficients:
(Intercept)   xsubject-2  
      4.373       -4.373  
```
and `$coef[-1])` is -4.373, subsequent plots are based on this result. 
This is in the case of dichotomous variables. And when there are multiple categorical variables, such as the Month variable in the sample data:
```
              y  x
L1S8   4.363669 10
L1S57  4.261257  1
L1S76  4.547193  2
L1S105 4.320939  3
L1S140 0.000000 10
L1S208 0.000000  1
L1S257 0.000000  3
L1S281 0.000000  4
```
when using _lm_, the result will be like this:
```
Coefficients:
(Intercept)          x10           x2           x3           x4  
    2.13063      0.05121      2.41656      0.02984     -2.13063
```
it will create four dummy variables: x10, x2, x3 and x4 (default to the variable 1 as the control variable). Due to this situation, the final result graph is composed of these 4 variables.

**I think categorical variables are not suitable for analysis using linear regression models.**

The above are the points that I am confused about the plot part of ancom, and in the analysis content of other parts, ancom has done a good job.

thanks a lot

**Comment by FrederickHuangLin** [comment]
Hi @wanjinhu,

Thanks for catching this! You are right, the volcano plot might have some problems when it comes to a categorical variable.

I will remove the volcano plot from the `ancom` function, and let people make the plots based on their own research needs. I think it will give people more flexibility.

Best,
Huang

**Comment by FrederickHuangLin** [comment]
Hi @wanjinhu,

I am happy to share with you that `ancom` function has been merged and published in our [ANCOMBC](https://www.bioconductor.org/packages/release/bioc/html/ANCOMBC.html) R package.

Please feel free to test it out and any feedback is highly appreciated!

Best,
Huang
