### ISSUE TITLE
ANCOM in larger dataset

### ISSUE THREAD

**Issue by YAYA530** [FrederickHuangLin/ANCOM-Code-Archive#46]
I tried analyzed biomarker in gene-level in metagenomics and I got one million non-redundant sequences and normalized by TPM (kind of compositional data). I narrow down the huge dataset via prevalence & abundance and got over 30,000 candidates. I want to further narrow down the dataset via ANCOM. Hence, I have query that whether I could split the 30,000 candidates into smaller dataset to perform ANCOM?

**Comment by FrederickHuangLin** [comment]
Hi @YAYA530,

ANCOM generally requires a large number of taxa to control the FDR. Based on our simulations, 100 - 500 taxa should be sufficient, and I would definitely recommend you to subset/split your candidates into smaller datasets or aggregate them to higher taxonomic levels (30,000 would take forever to run using ANCOM). 

Best,
Huang

**Comment by FrederickHuangLin** [comment]
Hi @YAYA530 ,

I am happy to share with you that `ancom` function has been merged and published in our [ANCOMBC](https://www.bioconductor.org/packages/release/bioc/html/ANCOMBC.html) R package, which now supports parallel computing!

Please feel free to test it out and any feedback is highly appreciated!

Best,
Huang
