### ISSUE TITLE
ANCOM plots

### ISSUE THREAD

**Issue by sunsvet** [FrederickHuangLin/ANCOM-Code-Archive#48]
Hello,

Thank you so much for this package. I have been getting strange figures from my analysis and can't figure out why, so I was hoping you could help me out.
I am currently running an analysis on shotgun metagenomics data. After filtering species with <10% presence, I have 318 species left and a sample of 97. I am currently comparing two groups (with 49 and 48 participants each). The plot I get looks nothing like a volcano plot. 
I get high significance, but it doesn't really make sense as the dots are very close to the 0 on the x axis. 
Do you have any idea what is going on?

![profiles_counts_trs_clz tsv ancom](https://user-images.githubusercontent.com/100886701/175849156-46865630-b358-4f74-bb47-99d00b0459e0.png)

![screenshot](https://user-images.githubusercontent.com/100886701/175849333-79af1385-10e5-4eed-ab98-1dd56ff2bfaa.jpg)

[profiles_counts_trs_clz.tsv.ancom.txt](https://github.com/FrederickHuangLin/ANCOM-Code-Archive/files/8988247/profiles_counts_trs_clz.tsv.ancom.txt)

Thanks so much for your time.

**Comment by FrederickHuangLin** [comment]
Hi @sunsvet,

Thanks for your interest in using ANCOM. The reason why you saw strange results of the volcano plot is that ANCOM does not reply on CLR mean differences as its effect sizes. Thus, W statistic and CLR mean differences are not closely related. We provide it soely for visualization convenience.

We realized it is not satisfying and decided to replace it with the cumulative W statistic plot for visualizations. You can see the tutorial [here](https://www.bioconductor.org/packages/release/bioc/vignettes/ANCOMBC/inst/doc/ANCOMBC.html#ancom-implementation).

Please note that the `ancom` function has been incorporated into our [ANCOMBC](https://www.bioconductor.org/packages/release/bioc/html/ANCOMBC.html) R package. This repository is only for the archive purpose and will no longer be maintained.

Thanks for using our software!

Best,
Huang
