### ISSUE TITLE
doubts regarding the use of metatranscriptome taxa table with ancom

### ISSUE THREAD

**Issue by sumitra20** [FrederickHuangLin/ANCOM-Code-Archive#51]
Hi @FrederickHuangLin,

I have been working on metatranscriptome samples using MEGAN6 pipeline. MEGAN6 allows us to import taxonimoc abundance table which is not exactly similar to OTU (example output files are attached here, i can either choose to get taxon path or list of specific family/class/genus/species)
[Comparison-leaf-allseason-complete-genus.txt](https://github.com/FrederickHuangLin/ANCOM-Code-Archive/files/10398416/Comparison-leaf-allseason-complete-genus.txt)
[Comparison-BS-allseason-xcomplete-ex-taxonpath-count.txt](https://github.com/FrederickHuangLin/ANCOM-Code-Archive/files/10398420/Comparison-BS-allseason-xcomplete-ex-taxonpath-count.txt)

Will i be able to use such output to run ANCOM? Also, MEGAN6  allows me to export the taxonomic output in biom1 format.

Thank you so much

**Comment by FrederickHuangLin** [comment]
Hi @sumitra20,

Please note this repository is only for archive purpose. For the most up-to-date `ancom` function, please visit the `ANCOMBC` R [package](https://www.bioconductor.org/packages/release/bioc/html/ANCOMBC.html).

Sorry I am not very familiar with MEGAN6 pipeline, but so long as this is not a normalized dataset, it should be fine to use the ANCOM method.

Best,
Huang
